### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by cenit** [tiemenschreuder/FortranCodeNav#3]
Dear Tiemen,
first of all thanks a lot for open sourcing your work.
I was looking for a simple solution that was performing some syntax highlighting for Fortran under Visual Studio 2017. From the [video](https://www.youtube.com/watch?v=ApumbtDAqMM) you're using in the description i was supposing that your extension was *also* doing it, but for me it is not.
Is it a known issue? If it is, I can look into your sources, since they are open ;)
Otherwise, please let me know what you did to enable syntax highlighting (I know there's VS Code and also many other editors, but I need something for the full VS 2017)

My setup: VS 15.9.5, Windows 10 1803

Thanks a lot!

**Comment by JHenneberg** [comment]
hey this plugin in is not for syntax highlighting. It is an intellisense like tool in early stage. Syntax highlighting for Fortran you can get by installing the Intel Fortran Tools for example. if you don't want to buy those you can use the editor atom for syntax highlighting and an excellent intellisense support due to a few plugins. The intellisense feature is working with a fortran-language-server in atom. The person who wrote the plugin for atom also wrote a tool for VS2017 which also communicates with the fortran-language-server but might have some flaws.

atom:
https://atom.io/
plugins:
https://atom.io/packages/ide-fortran
https://atom.io/packages/language-fortran


fortran-language-server:
https://github.com/hansec/fortran-language-server

**Comment by cenit** [comment]
Thanks for the prompt answer. As I told you I know about other editors, with a very good fortran support. I was looking for something for the *full* VS 2017, avoiding the Intel Fortran tools (which I would use only for syntax highlighting...). I will look for the vs2017 plugin written by the guy who wrote the atom plugin, thanks (btw, do you have any link?)

**Comment by JHenneberg** [comment]
Transitioning from VS to Atom/VS Code and being really satisfied so far I just wanted to do some advertising for some editors :). 

It is this extension for VS2017
https://github.com/michaelkonecny/vs-fortran-ls-client
using the fortran-language-server I mentioned previously. I did not test this particular extension only the fortran-language-server. But it is only mentioned on the git that it is not working niceley with Intel Fortran + VS2017 and because you are anyway not using it, this might work for you.

**Comment by cenit** [comment]
I also transitioned almost completely to VS Code. But the world surrounding us is big and really diversified... 
Thanks for the link :)
